#!/usr/bin/env python3
"""Generate _project/drop-list.md -- the control-plane inventory to strike through.

Classification comes from the per-path `servers` overrides the base author left
behind (SELF_HOSTED_CONTROL_PLANE_URL vs SELF_HOSTED_GATEWAY_URL). That is
Portkey's opinion, inherited and unverified, so this is a draft to react to and
not a source of truth.

It also computes the blast radius: how many component schemas each group owns
exclusively, and so would be orphaned if the group went away. Deleting paths is
easy; the schemas they drag with them are the part that gets missed.

Usage:
    _project/gen_drop_list.py
"""

from __future__ import annotations

import collections
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from build import HTTP_METHODS  # noqa: E402

CONTROL = "control plane"
GATEWAY = "gateway"
UNKNOWN = "unclassified"


def classify(item) -> str:
    urls = " ".join(str(s.get("url", "")) for s in (item.get("servers") or []))
    if "CONTROL_PLANE" in urls:
        return CONTROL
    if "GATEWAY" in urls:
        return GATEWAY
    return UNKNOWN


def refs_from(node, out: set) -> set:
    """Every #/components/... pointer reachable from a subtree."""
    if isinstance(node, dict):
        target = node.get("$ref")
        if isinstance(target, str) and target.startswith("#/components/"):
            out.add(target[len("#/components/"):])
        for value in node.values():
            refs_from(value, out)
    elif isinstance(node, list):
        for value in node:
            refs_from(value, out)
    return out


def resolve(spec, seeds: set) -> set:
    """Transitive closure: components reachable from a set of components."""
    components = spec.get("components") or {}
    seen, queue = set(), list(seeds)
    while queue:
        key = queue.pop()
        if key in seen:
            continue
        seen.add(key)
        section, _, name = key.partition("/")
        node = (components.get(section) or {}).get(name)
        if node is not None:
            queue.extend(refs_from(node, set()) - seen)
    return seen


def main() -> int:
    spec = yaml.safe_load((ROOT / "openapi.yaml").read_text())
    paths = spec["paths"]

    groups: dict[str, list[str]] = collections.defaultdict(list)
    reach: dict[str, set] = collections.defaultdict(set)
    for path, item in paths.items():
        if not isinstance(item, dict):
            continue
        kind = classify(item)
        groups[kind].append(path)
        refs_from(item, reach[kind])

    closure = {k: resolve(spec, v) for k, v in reach.items()}
    total = set().union(*closure.values()) if closure else set()

    lines = [
        "# Control-plane drop list",
        "",
        "Generated by `_project/gen_drop_list.py`. Regenerate after any change.",
        "",
        "**Tick a box to drop that path.** Every operation on a ticked path goes.",
        "To keep only some methods on a path, tick it and note which to keep.",
        "",
        "Classification is inherited from the base author's per-path `servers`",
        "overrides and is **unverified**. Treat it as a first draft, especially",
        f"the {len(groups[UNKNOWN])} unclassified paths, which need a call regardless.",
        "",
        "## Blast radius",
        "",
        "Components each group reaches, and how many *only* that group reaches",
        "(those are the ones orphaned if the group is dropped):",
        "",
        "| Group | Paths | Components reached | Reached only by this group |",
        "|---|---|---|---|",
    ]
    for kind in (CONTROL, GATEWAY, UNKNOWN):
        others = set().union(*(v for k, v in closure.items() if k != kind)) if closure else set()
        exclusive = closure[kind] - others
        lines.append(f"| {kind} | {len(groups[kind])} | {len(closure[kind])} "
                     f"| **{len(exclusive)}** |")
    lines += [
        f"| *total* | {sum(len(v) for v in groups.values())} | {len(total)} | |",
        "",
        f"Dropping every control-plane path would orphan "
        f"**{len(closure[CONTROL] - (closure[GATEWAY] | closure[UNKNOWN]))} components**, "
        "which must be pruned in the same change rather than left to accumulate.",
        "",
    ]

    for kind in (CONTROL, UNKNOWN, GATEWAY):
        note = {
            CONTROL: "The candidates. Tick what goes.",
            UNKNOWN: "No server override, so the base never said. **Needs a call.**",
            GATEWAY: "Data plane. Listed for completeness; expected to stay.",
        }[kind]
        lines += [f"## {kind.title()} — {len(groups[kind])} paths", "", note, ""]

        by_tag: dict[str, list[str]] = collections.defaultdict(list)
        for path in groups[kind]:
            tags = set()
            for method, op in paths[path].items():
                if method in HTTP_METHODS and isinstance(op, dict):
                    tags.update(op.get("tags") or [])
            by_tag[", ".join(sorted(tags)) or "(untagged)"].append(path)

        for tag in sorted(by_tag):
            lines += [f"### {tag}", ""]
            for path in sorted(by_tag[tag]):
                methods = sorted(m for m in paths[path] if m in HTTP_METHODS)
                ids = [paths[path][m].get("operationId") for m in methods]
                shown = ", ".join(
                    f"`{m.upper()}`" + (f" {i}" if i else " *(no operationId)*")
                    for m, i in zip(methods, ids)
                )
                lines.append(f"- [ ] `{path}` — {shown}")
            lines.append("")

    out = ROOT / "_project" / "drop-list.md"
    out.write_text("\n".join(lines))
    print(f"{sum(len(v) for v in groups.values())} paths -> {out}")
    for kind in (CONTROL, GATEWAY, UNKNOWN):
        print(f"    {kind:14} {len(groups[kind]):3} paths, "
              f"{len(closure[kind]):3} components reached")
    return 0


if __name__ == "__main__":
    sys.exit(main())
