#!/usr/bin/env python3
"""Generate _project/drop-list.md -- the plane inventory, with blast radius.

Classification comes from `_project/planes.yaml`, which is also what the build
reads to decide which paths get a control-plane server override. There is one
record of which plane a path is on and this reads it, so the inventory cannot
drift from the document it describes.

planes.yaml records *how* each call was made -- `classification.yaml` for the 23
a human decided, `inherited` for the rest, read off the base's per-path server
overrides before those were deleted and never independently verified. The output
marks which is which: a guess and a call should never be indistinguishable once
both are on the page.

It also computes the blast radius: how many component schemas each group owns
exclusively, and so would be orphaned if the group went away. Deleting paths is
easy; the schemas they drag with them are the part that gets missed.

Usage:
    _project/gen_drop_list.py
"""

from __future__ import annotations

import collections
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from build import HTTP_METHODS  # noqa: E402

CONTROL = "control plane"
GATEWAY = "gateway"
UNKNOWN = "unclassified"

CONTROL_KEY = "control-plane"
GATEWAY_KEY = "gateway"

# planes.yaml's `how` value for a path whose plane a human actually decided.
DECIDED_BY_HAND = "classification.yaml"


def load_planes(path: Path) -> tuple[dict[str, str], set[str]]:
    """{path: plane} and the subset a human decided, from planes.yaml."""
    doc = yaml.safe_load(path.read_text()) or {}
    plane_of: dict[str, str] = {}
    by_hand: set[str] = set()
    for key, kind in ((CONTROL_KEY, CONTROL), (GATEWAY_KEY, GATEWAY)):
        for p, how in (doc.get(key) or {}).items():
            plane_of[p] = kind
            if str(how).strip() == DECIDED_BY_HAND:
                by_hand.add(p)
    return plane_of, by_hand


def refs_from(node, out: set) -> set:
    """Every #/components/... pointer reachable from a subtree."""
    if isinstance(node, dict):
        target = node.get("$ref")
        if isinstance(target, str) and target.startswith("#/components/"):
            out.add(target[len("#/components/"):])
        for value in node.values():
            refs_from(value, out)
    elif isinstance(node, list):
        for value in node:
            refs_from(value, out)
    return out


def resolve(spec, seeds: set) -> set:
    """Transitive closure: components reachable from a set of components."""
    components = spec.get("components") or {}
    seen, queue = set(), list(seeds)
    while queue:
        key = queue.pop()
        if key in seen:
            continue
        seen.add(key)
        section, _, name = key.partition("/")
        node = (components.get(section) or {}).get(name)
        if node is not None:
            queue.extend(refs_from(node, set()) - seen)
    return seen


def main() -> int:
    spec = yaml.safe_load((ROOT / "openapi.yaml").read_text())
    paths = spec["paths"]

    plane_of, decided = load_planes(ROOT / "_project" / "planes.yaml")

    # Seeded for all three so an empty group -- which is the goal for
    # `unclassified` -- is a normal state and not a KeyError.
    groups: dict[str, list[str]] = {k: [] for k in (CONTROL, GATEWAY, UNKNOWN)}
    reach: dict[str, set] = {k: set() for k in (CONTROL, GATEWAY, UNKNOWN)}
    for path, item in paths.items():
        if not isinstance(item, dict):
            continue
        kind = plane_of.get(path, UNKNOWN)
        groups[kind].append(path)
        refs_from(item, reach[kind])

    closure = {k: resolve(spec, v) for k, v in reach.items()}
    total = set().union(*closure.values()) if closure else set()

    lines = [
        "# Plane inventory",
        "",
        "Generated by `_project/gen_drop_list.py` from `openapi.yaml` and",
        "`_project/planes.yaml`, so it shows what the specification **currently",
        "ships** -- paths already dropped are gone from it. Regenerate after any",
        "change.",
        "",
        "> Decisions do not live here. This file is generated and any mark made in it",
        "> is lost on the next run. The durable record of what is not shipped is",
        "> `_project/drops.yaml`, enforced by `scripts/build.py`; the record of which",
        "> plane a path is on is `_project/planes.yaml`. Change those.",
        "",
        (f"**{len(groups[UNKNOWN])} paths are missing from planes.yaml** and need a"
         " call -- the build fails until they have one."
         if groups[UNKNOWN] else
         "**Every path is classified.** The build fails if one is not."),
        "",
        "**✓** marks a path a human classified, recorded in `planes.yaml` as coming"
        f" from `classification.yaml` ({len(decided)} of {len(plane_of)}).",
        "Everything unmarked was read off the base's per-path server overrides before",
        "those were deleted, and is **unverified**.",
        "",
        "## Blast radius",
        "",
        "Components each group reaches, and how many *only* that group reaches",
        "(those are the ones orphaned if the group is dropped):",
        "",
        "| Group | Paths | Components reached | Reached only by this group |",
        "|---|---|---|---|",
    ]
    for kind in (CONTROL, GATEWAY, UNKNOWN):
        others = set().union(*(v for k, v in closure.items() if k != kind)) if closure else set()
        exclusive = closure[kind] - others
        lines.append(f"| {kind} | {len(groups[kind])} | {len(closure[kind])} "
                     f"| **{len(exclusive)}** |")
    lines += [
        f"| *total* | {sum(len(v) for v in groups.values())} | {len(total)} | |",
        "",
        f"Dropping every control-plane path would orphan "
        f"**{len(closure[CONTROL] - (closure[GATEWAY] | closure[UNKNOWN]))} components**, "
        "which must be pruned in the same change rather than left to accumulate.",
        "",
    ]

    for kind in (CONTROL, UNKNOWN, GATEWAY):
        note = {
            CONTROL: "Control-plane paths that survive the drops in `drops.yaml`.",
            UNKNOWN: "Absent from `planes.yaml`. **Needs a call** -- add it there, "
                     "or the build refuses to run.",
            GATEWAY: "Data plane. Listed for completeness; expected to stay.",
        }[kind]
        lines += [f"## {kind.title()} — {len(groups[kind])} paths", ""]
        if not groups[kind]:
            lines += ["None. Every path in the specification has been classified.", ""]
            continue
        lines += [note, ""]

        by_tag: dict[str, list[str]] = collections.defaultdict(list)
        for path in groups[kind]:
            tags = set()
            for method, op in paths[path].items():
                if method in HTTP_METHODS and isinstance(op, dict):
                    tags.update(op.get("tags") or [])
            by_tag[", ".join(sorted(tags)) or "(untagged)"].append(path)

        for tag in sorted(by_tag):
            lines += [f"### {tag}", ""]
            for path in sorted(by_tag[tag]):
                methods = sorted(m for m in paths[path] if m in HTTP_METHODS)
                ids = [paths[path][m].get("operationId") for m in methods]
                shown = ", ".join(
                    f"`{m.upper()}`" + (f" {i}" if i else " *(no operationId)*")
                    for m, i in zip(methods, ids)
                )
                mark = " ✓" if path in decided else ""
                lines.append(f"- [ ] `{path}`{mark} — {shown}")
            lines.append("")

    out = ROOT / "_project" / "drop-list.md"
    out.write_text("\n".join(lines))
    print(f"{sum(len(v) for v in groups.values())} paths -> {out}")
    for kind in (CONTROL, GATEWAY, UNKNOWN):
        print(f"    {kind:14} {len(groups[kind]):3} paths, "
              f"{len(closure[kind]):3} components reached")
    return 0


if __name__ == "__main__":
    sys.exit(main())
